export const SET_ITEM_PRODUCTS = "SET_ITEM_PRODUCTS";
export const SET_LOADER_PRODUCTS = "SET_LOADER_PRODUCTS";
export const SET_FILTER_PRODUCTS = "SET_FILTER_PRODUCTS";
export const SET_CATEGORY_WRAPPER = "SET_CATEGORY_WRAPPER";
export const SET_SUB_CATEGORY_WRAPPER = "SET_SUB_CATEGORY_WRAPPER";
