export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const UPDATE_STRUCTURE_DATA = "UPDATE_STRUCTURE_DATA";
export const GET_STRUCTURE_DATA = "GET_STRUCTURE_DATA";
export const SET_AUTH_USER = "SET_AUTH_USER";
export const SET_COUNTER_LINE = "SET_COUNTER_LINE";
export const SET_LOUADER_COUNTER = "SET_LOUADER_COUNTER";
export const GO_DOWN_PAGE = "GO_DOWN_PAGE";
